apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: jilsx/multi-client
          ports: 
            - containerPort: 3000
        - name: server
          image: jilsx/multi-server
          ports: 
            - containerPort: 5000
